Automating Secrets Management with 1Password Connect
octoenergy/octoenergy.github.io pull request #76
Opened 2024-08-28 14:05 UTC by MajaCernja

A write up with learnings from data platform's implementation of 1Password Connect for secrets management automation.

2024-08-28 15:49 UTC, frederizia reviewed
I like this! Have left a few nitpicky comments.

2024-08-28 15:49 UTC, frederizia commented on _posts/2024-08-28-onepassword-connect.markdown
> +Here at Kraken Tech the data platform team is in charge of building out comprehensive analytics platforms for all our clients. This includes setting up ingestion pipelines, orchestration of tasks, da
Small thing but we tend to start all our posts with "Here at Kraken" or similar, and we show previews on the page so it's starting to get a bit awkward. We also just say "Kraken" not "Kraken Tech" now I think.

<img width="1040" alt="Screenshot 2024-08-28 at 16 25 54" src="https://github.com/user-attachments/assets/7c1297ba-966f-48fd-a26f-000b216183ea">

2024-08-28 15:49 UTC, frederizia commented on _posts/2024-08-28-onepassword-connect.markdown
> +Here at Kraken Tech the data platform team is in charge of building out comprehensive analytics platforms for all our clients. This includes setting up ingestion pipelines, orchestration of tasks, da
Would maybe link to some website for `dbt`, `1Password` etc in case someone is not familiar.

2024-08-28 15:49 UTC, frederizia commented on _posts/2024-08-28-onepassword-connect.markdown
> +Kubernetes secrets are needed for all our services to run smoothly and safely for each client. And at our scale it became necessary to automate the creation and updating of secrets. We explored other
I think there is an extra space right at the end?

2024-08-28 15:49 UTC, frederizia commented on _posts/2024-08-28-onepassword-connect.markdown
> +* 1Password was already our default credential manager and the OP Connect Server meant we could rely on 1Password to be the **single source of truth** for credential values
These should have full stops at the end as they're full sentences.

2024-08-28 15:49 UTC, frederizia commented on _posts/2024-08-28-onepassword-connect.markdown
> +* We could be confident that whatever is saved in 1Password will be reflected in Kubernetes, i.e. the **updates to credentials in 1Password would be automatically refreshed downstream**
I think it reads better as "would automatically be refreshed"

2024-08-28 15:49 UTC, frederizia commented on _posts/2024-08-28-onepassword-connect.markdown
> +* Significant **reduction in manual steps and thus human error** during credential generation and secret updates
Does this not apply generally for any automatic solution? Why in particular for this solution?

2024-08-28 15:49 UTC, frederizia commented on _posts/2024-08-28-onepassword-connect.markdown
> +* We could be confident that whatever is saved in 1Password will be reflected in Kubernetes, i.e. the **updates to credentials in 1Password would be automatically refreshed downstream**
Maybe phrase this more as "updating credentials is a single step process as the changes in 1password are automatically refreshed downstream" or similar?

2024-08-28 15:49 UTC, frederizia commented on _posts/2024-08-28-onepassword-connect.markdown
> +Here at Kraken Tech the data platform team is in charge of building out comprehensive analytics platforms for all our clients. This includes setting up ingestion pipelines, orchestration of tasks, da
Ah you're linking some 1pw docs later down the line 👍

2024-08-28 15:49 UTC, frederizia commented on _posts/2024-08-28-onepassword-connect.markdown
> +The Connect servers and Connect tokens need to be granted access to the  relevant vaults, where the credentials you wish to sync into secrets are stored. Hence, for smooth OP Connect implementation,
extra space between "to the relevant vaults"?

2024-08-28 15:49 UTC, frederizia commented on _posts/2024-08-28-onepassword-connect.markdown
> +**Creating a Connect Server != Deploying Connect Server**
This could be a `###` too right? Any reason why you chose to just make it bold?

2024-08-28 15:49 UTC, frederizia commented on _posts/2024-08-28-onepassword-connect.markdown
> +Creating the Connect server with the OP CLI does not deploy the server, it simply  creates the configuration for the 1Password connect server and the JSON file which contains the blueprint to deploy
Another double space? Am I imagining these? Is it just something around how GH renders this? 😅

2024-08-28 15:49 UTC, frederizia commented on _posts/2024-08-28-onepassword-connect.markdown
> +## Key Learnings
I think this is a really nice thing to share in a blog!

2024-08-28 15:49 UTC, frederizia commented on _posts/2024-08-28-onepassword-connect.markdown
> +A little [quirk](https://1password.community/discussion/131378/loadlocalauthv2-failed-to-credentialsdatafrombase64) to be aware of, we ran into this one during debugging one of the first attempts to
I'd probably switch the two around and make them separate sentences. Or properly connect them (which we ran into..).

2024-08-28 15:49 UTC, frederizia commented on _posts/2024-08-28-onepassword-connect.markdown
> +* `pollingInterval` – specifies how frequently the Kubernetes Operator checks in on 1password items, i.e. this is the maximum delay between creating or updating an item and seeing the change be refle
Do you have an indication you can share on which interval you have found useful? E.g. some kind of "for our use case, we found xxx to be a good interval length".

2024-08-28 15:49 UTC, frederizia commented on _posts/2024-08-28-onepassword-connect.markdown
> +* `autoRestart` – determines whether or not to perform a rolling restart on deployments in the relevant namespace when a secret is updated, so that the updated secret is in use as soon as possible, i
The last bit should be its own sentence, this is just a little long. Generally could be more explicit, e.g. something like "when enabled, the updated secret is in use as soon as possible".

2024-08-28 15:49 UTC, frederizia commented on _posts/2024-08-28-onepassword-connect.markdown
> +**Common Pitfalls**
I'm not sure this section feels different enough from "key learnings" to be its own thing, though I also can't quite think of a good way of making it fit with key learnings.

2024-08-28 15:49 UTC, frederizia commented on _posts/2024-08-28-onepassword-connect.markdown
> +* `Reconciller error` – This one crops up in the Kubernetes logs and indicates that secret syncing isn’t working. One cause we’ve come across was an invalid OP connect token. Another was deleting and
Reconciler not Reconciller?

2024-08-28 15:49 UTC, frederizia commented on _posts/2024-08-28-onepassword-connect.markdown
> +* `Reconciller error` – This one crops up in the Kubernetes logs and indicates that secret syncing isn’t working. One cause we’ve come across was an invalid OP connect token. Another was deleting and
You usually capitalise connect

2024-08-28 15:49 UTC, frederizia commented on _posts/2024-08-28-onepassword-connect.markdown
> +* `Reconciller error` – This one crops up in the Kubernetes logs and indicates that secret syncing isn’t working. One cause we’ve come across was an invalid OP connect token. Another was deleting and
An interesting addition would be if you put monitoring in place for this? Is this something that happens frequently or just initially when you're trying things out?

2024-09-02 11:13 UTC, codeinthehole requested changes
Thanks for this! Love to see more blog posts.

I've added some very, very minor 🐼 points (sorry)

2024-09-02 11:13 UTC, codeinthehole commented on _posts/2024-08-28-onepassword-connect.markdown
> +title: Automating Secrets Management with 1Password Connect
🐼 Prior titles are sentence-case (not title-case)

2024-09-02 11:13 UTC, codeinthehole commented on _posts/2024-08-28-onepassword-connect.markdown
> +Here at Kraken Tech the data platform team is in charge of building out comprehensive analytics platforms for all our clients. This includes setting up ingestion pipelines, orchestration of tasks, da
Should "dbt" be capitalised?

2024-09-02 11:13 UTC, codeinthehole commented on _posts/2024-08-28-onepassword-connect.markdown
> +## Why 1Password Connect
🐼 Needs a question mark?

2024-09-02 11:13 UTC, codeinthehole commented on _posts/2024-08-28-onepassword-connect.markdown
> +**Creating a Connect Server != Deploying Connect Server**
🐼 Agree that we should use heading mark-up for all these subheadings.

2024-09-02 11:24 UTC, MajaCernja commented on _posts/2024-08-28-onepassword-connect.markdown
> +**Common Pitfalls**
Yeah I had the same dilemma, keeping it within 'Key Learnings' seemed slightly better

2024-09-02 11:29 UTC, MajaCernja commented on _posts/2024-08-28-onepassword-connect.markdown
> +**Creating a Connect Server != Deploying Connect Server**
Yep, I initially used `###` but thought it looked a bit nicer if I bold it instead, attaching screenshots

Header 
<img width="942" alt="Screenshot 2024-09-02 at 12 26 15" src="https://github.com/user-attachments/assets/0050b206-774b-4c3b-8ba9-d8db3c6bbd32">

Bold
<img width="900" alt="Screenshot 2024-09-02 at 12 25 36" src="https://github.com/user-attachments/assets/365c17a6-8ad7-4b23-bbb7-1619da0386f8">

2024-09-02 11:56 UTC, MajaCernja commented on _posts/2024-08-28-onepassword-connect.markdown
> +Here at Kraken Tech the data platform team is in charge of building out comprehensive analytics platforms for all our clients. This includes setting up ingestion pipelines, orchestration of tasks, da
I don't think so, none of their official docs capitalise it (attached an example)

<img width="675" alt="Screenshot 2024-09-02 at 12 53 17" src="https://github.com/user-attachments/assets/6e3cec0e-aaf7-46f6-b07a-121aa430571b">

2024-09-05 13:19 UTC, frederizia approved these changes
A few more comments but it's not really blocking. Well done and thank you!

2024-09-05 13:19 UTC, frederizia commented on _posts/2024-09-02-onepassword-connect.markdown
> +* A particularly **user-friendly experience** compared to alternatives. For example, 1password web UI contains a developer tools section which lists out existing connect servers, whether they have be
🐼 "for example _the_ 1password web UI... which lists existing..." (or is out -> our?)

2024-09-05 13:19 UTC, frederizia commented on _posts/2024-09-02-onepassword-connect.markdown
> +Another important step was choosing **where to store the Connect token and credentials JSON** needed for each Connect deployment. We spent a good amount of time discussing with our security team how
🐼 discussing .... with our security team

2024-09-05 13:19 UTC, frederizia commented on _posts/2024-09-02-onepassword-connect.markdown
> +### Name your servers well
You kind of touch on the naming above so this feels a bit like a repeat.

2024-09-05 13:19 UTC, frederizia commented on _posts/2024-09-02-onepassword-connect.markdown
> +We are currently looking into setting up a dashboard to proactively monitor for Connect related errors. The main reason we did not set this up immediately is because the simplest solution would requi
Are we still investigating this or is the conclusion that it's not possible?

2024-09-05 13:19 UTC, frederizia commented on _posts/2024-09-02-onepassword-connect.markdown
> +1Password Connect has become an integral part of a more automated credential and secrets management workflow across the many deployment environments we support, reducing the need for manual involveme
🐼 "reducing the need for manual involvement and the room for human error." reads a bit weird to me. Maybe adding a "hence" helps? "reducing the need for manual involvement and hence the room for human error."

2024-09-05 16:11 UTC, MajaCernja commented on _posts/2024-09-02-onepassword-connect.markdown
> +We are currently looking into setting up a dashboard to proactively monitor for Connect related errors. The main reason we did not set this up immediately is because the simplest solution would requi
Still investigating, will make it clearer.

2024-09-05 18:17 UTC, codeinthehole approved these changes

2024-09-12 08:30 UTC, merged